stages:
  - build

build_cligen:
  stage: build
  script:
    - cd cligen532
    - make all
  artifacts:
    paths:
      - cligen532/cligen532
      - cligen532/cligen532_backtrace
    expire_in: 1 week
