stages:
  - build

build_linux_cligen:
  stage: build
  tags:
    - forest-linux-shell-fortran
  script:
    - cd cligen532
    - make clean
    - make all
  artifacts:
    paths:
      - cligen532/cligen532
      - cligen532/cligen532_backtrace
    expire_in: 1 week