c    File: cbk3.inc
c
C     common /bk3/ alai(5),salb(5),dm(5),rd(5),uw,ep,es,rain,ws,
C    1             je,j,ida
      common /bk3/ j,ida
c
c     alai        - Never seems to get used -- CRM -- 10/20/99
c     salb        - Never seems to get used -- CRM -- 10/20/99
c     dm          - Never seems to get used -- CRM -- 10/20/99
c     rd          - Never seems to get used -- CRM -- 10/20/99
c     uw          - Never seems to get used -- CRM -- 10/20/99
c     ep          - Never seems to get used -- CRM -- 10/20/99
c     es          - Never seems to get used -- CRM -- 10/20/99
c     rain        - Never seems to get used -- CRM -- 10/20/99
c     ws          - Never seems to get used -- CRM -- 10/20/99
c     je          - Never seems to get used -- CRM -- 10/20/99
c     j           - Loop index.  (WHY is it in a COMMON BLOCK?!?)
c     ida         - Julian Day of Year.  Used as a subscript to R.
c
