c    File: cbk5.inc
c
C     common /bk5/ r(366),vmx(5),v(5),flu(6),bp(5),hc(5),hcr(5),fp(5),
C    1             cs(5),sk(5),smx(5),ev,sp,rl,q1,o,qd,af,pq,yp,aff,
C    1             amps,cn,sml,cfp(5),swm(5),sfc(5),dk(5)
      common /bk5/ r(366),sml
c     r           - Daily Precipitation amount (inches of water)
c     vmx         - Never seems to get used -- CRM -- 10/21/99
c     v           - Never seems to get used -- CRM -- 10/21/99
c     flu         - Never seems to get used -- CRM -- 10/21/99
c     bp          - Never seems to get used -- CRM -- 10/21/99
c     hc          - Never seems to get used -- CRM -- 10/21/99
c     hcr         - Never seems to get used -- CRM -- 10/21/99
c     fp          - Never seems to get used -- CRM -- 10/21/99
c     cs          - Never seems to get used -- CRM -- 10/21/99
c     sk          - Never seems to get used -- CRM -- 10/21/99
c     smx         - Never seems to get used -- CRM -- 10/21/99
c     ev          - Never seems to get used -- CRM -- 10/21/99
c     sp          - Never seems to get used -- CRM -- 10/21/99
c     rl          - Never seems to get used -- CRM -- 10/21/99
c     q1          - Never seems to get used -- CRM -- 10/21/99
c     o           - Never seems to get used -- CRM -- 10/21/99
c     qd          - Never seems to get used -- CRM -- 10/21/99
c     af          - Never seems to get used -- CRM -- 10/21/99
c     pq          - Never seems to get used -- CRM -- 10/21/99 
c     yp          - Never seems to get used -- CRM -- 10/21/99 
c     aff         - Never seems to get used -- CRM -- 10/21/99
c     amps        - Never seems to get used -- CRM -- 10/21/99
c     cn          - Never seems to get used -- CRM -- 10/21/99
c     sml         - Used to compute R1.
c     cfp         - Never seems to get used -- CRM -- 10/21/99
c     swm         - Never seems to get used -- CRM -- 10/21/99
c     sfc         - Never seems to get used -- CRM -- 10/21/99
c     dk          - Never seems to get used -- CRM -- 10/21/99
c
